### ISSUE TITLE
Helper/Informational functions

### ISSUE THREAD

**Issue by ecjbosu** [r-lib/R6#112]
It would be nice to have helper/inforational functions for R6 classes.
1. public(private)Fields : would return all public fields/slots
2. public(private)Methods: would return all public(private)
3 get showMethods or method to work with R6 classes.

These are very helpful for initialization and dynamic programming of objects.

Thank you very much
Joe

**Comment by hadley** [comment]
You can already use `names()` to return all public fields/methods.

I don't think R6 should expose a list of private fields/methods. They are private!
