### ISSUE TITLE
Throw error if field does not exist?

### ISSUE THREAD

**Issue by hadley** [r-lib/R6#123]
```R
X <- R6Class("X")
x <- X$new()

x$X
```

Why isn't this an error?

**Comment by wch** [comment]
For the same reason this isn't an error:

```R
e <- new.env()
e$x
# NULL
```

Changing the behavior would require adding a `$.R6` method, but it would add a significant performance penalty.

**Comment by hadley** [comment]
Oh, right, I keep forgetting that we can't have a `$` method 😞

**Comment by hadley** [comment]
It occurs to me that we might be able to make this fast by using object tables. Worth at least a small exploration.

**Comment by hadley** [comment]
object tables turn out to be fairly slow, so unlikely to be worth it.
