### ISSUE TITLE
R6 package will not load in R version 3.2.5

### ISSUE THREAD

**Issue by Melissa-Cruz** [r-lib/R6#132]
Is there a way to load this package  in R version 3.2.5? My workplace uses  R version 3.2.5 on their servers. We receive this error "Warning in install.packages : installation of package ‘R6’ had non-zero exit status".  Any suggestions would be great! 

Thank you!

**Comment by wch** [comment]
R6 should install just fine in R 3.2.5. Can you provide the full output from when you try to install it? Also please include the output of `sessionInfo()` or `devtools::session_info()`.

**Comment by Melissa-Cruz** [comment]
Here's the full output:

install.packages('R6', dependencies=TRUE, repos='http://cran.rstudio.com/')
Installing package into ‘C:/Users/~/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
   binary source needs_compilation
R6  2.2.0  2.2.2             FALSE

installing the source package ‘R6’

trying URL 'http://cran.rstudio.com/src/contrib/R6_2.2.2.tar.gz'
Content type 'application/x-gzip' length 322959 bytes (315 KB)
downloaded 315 KB

'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  running command '"D:/Program Files/R/R-3.2.5/bin/x64/R" CMD INSTALL -l "C:\Users\~\Documents\R\win-library\3.2" C:\Users\~\Temp\64\Rtmp2jtmMW/downloaded_packages/R6_2.2.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘R6’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\~Temp\64\Rtmp2jtmMW\downloaded_packages’


Here's the sessionInfo:
 sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.5




Thank you!

**Comment by wch** [comment]
I think this is probably due to a bug in R itself when dealing with volumes where short filenames are disabled. I would wager that you are unable to install any packages on your system, not just R6.

For more information:
  * r-lib/remotes#98
  * https://stat.ethz.ch/pipermail/r-devel/2017-September/074921.html
  * hadley/devtools#1514

**Comment by Melissa-Cruz** [comment]
Interesting. I do have certain restrictions on  my work system but I was able to install another package like haven, which wasn't previously present just not R6. I'll check back with IT. 

Thank you for your suggestions.

**Comment by wch** [comment]
Using `install.packages("R6", type = "binary")` may work, although you'd get an older version of R6.

**Comment by Melissa-Cruz** [comment]
That worked! Thanks

**Comment by k-rama** [comment]
> Using `install.packages("R6", type = "binary")` may work, although you'd get an older version of R6.

Had a similar problem when running ggfortify for ggplot, that solved it. Thank you
