### ISSUE TITLE
Check Class Name Internally?

### ISSUE THREAD

**Issue by cdeterman** [r-lib/R6#135]
Is there a way to have an R6 class return the name of it's class.  For example:

```r
myClass <- R6Class(
    "myClass",
    public = list(
        getClass = function(){
            #print(self$classname)
        }
     )
)
```

I would expect it to return `"myClass"`

I could simply add another field internally that simply populates `self$classname` as the class but I didn't know if there was an internal method already implemented like you would see with a python class like this `self.__class__.__name__`.

**Comment by wch** [comment]
You could do something like this:

```R
myClass <- R6Class(
  "myClass",
  public = list(
    getClass = function(){
      class(self)[1]
    }
  )
)

m <- myClass$new()

m$getClass()
#> [1] "myClass"
```
