### ISSUE TITLE
Returning invisible(self) in print method prevents the object to be gc'ed

### ISSUE THREAD

**Issue by Enchufa2** [r-lib/R6#140]
I'm not sure about what's going on here. This works ok:

```r
library(R6)

Person <- R6Class("Person",
  public = list(
    initialize = function() {
      self
    },
    print = function() {
      cat(paste0("Hello, world!\n"))
      # invisible(self)
    },
    finalize = function() {
      message("Finalizer has been called!")
    }
  )
)
Person$new()
gc() # still in .Last.value
gc() # Finalizer has been called!
```

The object is gc'ed in the second call as expected, because in the first call, the object is still accessible through `.Last.value`. But if we return `invisible(self)` from the print method, as #125 says and as every `print` method in R does, the object is not gc'ed:

```r
library(R6)

Person <- R6Class("Person",
  public = list(
    initialize = function() {
      self
    },
    print = function() {
      cat(paste0("Hello, world!\n"))
      invisible(self)
    },
    finalize = function() {
      message("Finalizer has been called!")
    }
  )
)
Person$new()
gc() # still in .Last.value
gc() # nothing...
```

But if we print something else, then the object is gc'ed!

```r
print(1)
gc() # Finalizer has been called!
```

**Comment by wch** [comment]
I suspect the root cause is that R is doing some sort of caching for printed objects. I'm not sure whether this is a bug in R, or if there's a good reason for it.

The same thing happens with this code:

```R
print.foo <- function(x, ...) {
  cat("print.foo called\n")
  invisible(x)
}

new_foo <- function() {
  e <- new.env()
  reg.finalizer(e, function(e) message("Finalizer called"))
  class(e) <- "foo"
  e
}

new_foo()
gc() # still in .Last.value
gc() # nothing
```

If the last line of `new_foo()` is changed from `e` to `invisible(e)`, then it does run the finalizer on the second `gc()`.

**Comment by wch** [comment]
It might actually be due to caching in R's S3 dispatch mechanism. For example, this executes the finalizer:

```R
ident <- function(x) invisible(x)

new_foo <- function() {
  e <- new.env()
  reg.finalizer(e, function(e) message("Finalizer called"))
  class(e) <- "foo"
  e
}

ident(new_foo())
gc()
gc() # Finalizer called
```

But this doesn't:

```R
ident <- function(x) UseMethod("ident")
ident.foo <- function(x) invisible(x)

new_foo <- function() {
  e <- new.env()
  reg.finalizer(e, function(e) message("Finalizer called"))
  class(e) <- "foo"
  e
}

ident(new_foo())
gc()
gc() # Nothing
```

**Comment by Enchufa2** [comment]
You are right, nice analysis!

So, is this a bug or a *feature*? Do you think I should report this in R-devel?

**Comment by Enchufa2** [comment]
BTW, closing this, as it has nothing to do with R6.

**Comment by wch** [comment]
It might be worth reporting to r-devel, or at least asking if it's expected behavior.

**Comment by Enchufa2** [comment]
I was about to post in R-devel and...

Did you try your examples (and mine) in a plain R console? I think it's RStudio...

**Comment by Enchufa2** [comment]
Ok, I'm trying to gather the final bits. It was R 3.2.3 (don't ask...) the one that succeeded. R 3.4.3 fails miserably with or without RStudio. It's R after all. Someone with quick access to R 3.3.x?

**Comment by Enchufa2** [comment]
Checked. It fails in R 3.3.2 too. Writing to R-devel...

**Comment by Enchufa2** [comment]
For the sake of completeness, if somebody lands here, Luke Tierney explains the issue [here](https://stat.ethz.ch/pipermail/r-devel/2018-March/075765.html). It turns out that it has nothing to do with S3 dispatch, but with an internal register being protected as a result of a explicit return. The following example shows the same issue without S3:

```r
new_foo <- function() {
  e <- new.env()
  reg.finalizer(e, function(e) message("Finalizer called"))
  e
}

bar <- function(x) return(x)

bar(new_foo())
gc() # still in .Last.value
gc() # nothing
```

The internal register gets cleared as soon as there is *another* explicit return:

```r
bar(1)
gc() # Finalizer called
```

Note that the important bit is the **explicit** return. If we remove it, the issue disappears:

```r
new_foo <- function() {
  e <- new.env()
  reg.finalizer(e, function(e) message("Finalizer called"))
  e
}

bar <- function(x) x

bar(new_foo())
gc() # still in .Last.value
gc() # Finalizer called!
```
