### ISSUE TITLE
Package is large

### ISSUE THREAD

**Issue by wch** [r-lib/R6#150]
When installing the binary package, I saw this:

```
> install.packages("R6")
Installing package into ‘/Users/winston/R/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/R6_2.2.2.tgz'
Content type 'application/x-gzip' length 321100 bytes (313 KB)
==================================================
downloaded 313 KB
```

The main culprit is the vignettes; the actual code for R6 is pretty small.

Perhaps some or all of the vignettes should be migrated to a website using pkgdown.

**Comment by gaborcsardi** [comment]
You could create a pkgdown site and  omit the formatted vignettes from the package.
