### ISSUE TITLE
Active bindings turned into constants during package build

### ISSUE THREAD

**Issue by mllg** [r-lib/R6#152]
Here is a small package to illustrate the issue:

https://github.com/mllg/r6pkg

Everything works out fine while loading the package interactively (using devtools' `load_all()`):
```
load_all()
print(bar)
<foo>
  Public:
    clone: function (deep = FALSE)
    x: 10
    x_squared: active binding
```

The active binding is lost after installing and loading the package in a fresh R session via `library()`:
```
library(r6pkg)
print(bar)
<foo>
  Public:
    clone: function (deep = FALSE)
    x: 10
    x_squared: 100
```
Looks like the binding gets evaluated during R CMD build and the returned value is stored instead.

**Comment by wch** [comment]
It looks like this is what R does in packages: active bindings get saved as regular values.

If you add this to your package, the same thing happens:

```R
#' @export
e <- new.env()
makeActiveBinding("x", function() runif(1), e)
```


Then after installing the package:

```R
e$x
#> [1] 0.1425588
e$x
#> [1] 0.1425588
bindingIsActive("x", e)
#> [1] FALSE
```

Perhaps it's worth asking about on the R-devel mailing list?

**Comment by mllg** [comment]
Can confirm this one. I've updated the package to also include your code.
```r
> library(r6pkg)
> unique(replicate(10, r6$x))
[1] 0.5698038
> unique(replicate(10, env$x))
[1] 0.262672
```

@kalibera, is this related to the bytecode compiler?

**Comment by mllg** [comment]
NB: `saveRDS()` + `loadRDS()` is not affected.

**Comment by kalibera** [comment]
Active bindings are preserved on serialization/deserialization, but one has to serialize them as bindings (not values) - so one has to serialize at least the environment they are part of.

**Comment by kalibera** [comment]
Active bindings are however not preserved when a package is being prepared for lazy loading (during package installation). The lazy loading database is already created with concrete values for active bindings.

**Comment by mllg** [comment]
So this is a feature, not a bug? 😕

**Comment by mllg** [comment]
Workaround: construct objects with active bindings in `.onLoad()`.
