### ISSUE TITLE
str() is slow for R6 objects containing large vectors

### ISSUE THREAD

**Issue by kevinushey** [r-lib/R6#159]
```R
library(R6)
Big <- R6Class("Big", public = list(data = rnorm(1E7)))
big <- Big$new()
system.time(str(big))
#> Classes 'Big', 'R6' <Big>
#>   Public:
#>     clone: function (deep = FALSE) 
#>     data: -0.594100136328869 0.104513371816434 0.531537555504934 - ...
#>    user  system elapsed 
#>  19.191   0.417  19.630
```

See also: https://github.com/rstudio/rstudio/issues/3544

Could R6 subset large vectors before calling `str()`?

**Comment by gaborcsardi** [comment]
Seems like `str` calls `format` and the `format.R6` method is slow.

**Comment by wch** [comment]
It looks most of the time is spent in this `paste()`:

https://github.com/r-lib/R6/blob/1c1f42576a49b6a08a4ef52f154026f8f01531f0/R/print.R#L114

Given that the subsequent `trim()` call uses the default width of 60 characters, I suppose it would be OK to do something like:

```R
  paste(as.character(head(obj, 60))
```

Do you guys see anything that I'm overlooking?

**Comment by gaborcsardi** [comment]
I think `head()` is  a good idea. But it only works for objects with a `[` method, so you would need some fallback, maybe just `format(x)` or the  class of  the  object, like `<environment>`:

```r
❯ head(environment())
Error in x[seq_len(n)] : object of type 'environment' is not subsettable

❯ head(ps::ps_handle())
Error in x[seq_len(n)] : object of type 'externalptr' is not subsettable

❯ format(environment())
[1] "<environment: R_GlobalEnv>"

❯ format(ps::ps_handle())
[1] "<ps::ps_handle> PID=18088, NAME=R, AT=2018-09-26 20:00:02"
```

**Comment by gaborcsardi** [comment]
Btw. there are some possibly related changes in R-3.5.1-patched, it has a workaround for `print(runif(1e7))` taking a long time, i.e. it  subsets using `getOption(max.print)` before doing the formatting. Maybe it is worth checking if `format` was also fixed there. OTOH we want to fix older R versions as well...

**Comment by wch** [comment]
But `head()` should work for the `is.atomic()` case, right? For the other cases you listed, it would already print them out in different ways.

**Comment by gaborcsardi** [comment]
Yes, for `is.atomic` is should work fine, I think.
