### ISSUE TITLE
assigning function from another namespace via `set` strips function of original environment

### ISSUE THREAD

**Issue by yonicd** [r-lib/R6#164]
I am trying to place a function from a installed package using `set`, in the example below `stats::rbinom`.

the function's environment is replaced when initializing on the R6 class. This causes the runction itself not to be able to run since it can't locate non exported functions from the parent namespace.

Is there a simple way to do this in R6?

``` r
Simple <- R6::R6Class("Simple",
                      public = list(
                        x = 1,
                        getx = function() self$x
                      )
)

Simple$set(which = 'public',name = 'foo',stats::rbinom)

Simple$public_methods$foo
#> function (n, size, prob) 
#> .Call(C_rbinom, n, size, prob)
#> <bytecode: 0x7f9c3dc78ab8>
#> <environment: namespace:stats>

obj <- Simple$new()

get('foo',envir = obj)
#> function (n, size, prob) 
#> .Call(C_rbinom, n, size, prob)
#> <environment: 0x7f9c3dee7e38>

obj$foo(n = 1,size = 0,prob = .3)
#> Error in obj$foo(n = 1, size = 0, prob = 0.3): object 'C_rbinom' not found
```

<sup>Created on 2018-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wch** [comment]
Any members of `Simple` that are functions are considered methods, and so they'll have their environment changed when an object of class Simple is instantiated.

If you want to work around this, you can either:

Assign `foo` in the `initialize` method:

```R
Simple <- R6::R6Class("Simple",
  public = list(
    initialize = function() {
      self$foo <- stats::rbinom
    },
    foo = NULL
  )
)
```

Make `foo` a wrapper function that calls the function you want.

```R
Simple <- R6::R6Class("Simple",
  public = list(
    foo = function(...) stats::rbinom(...)
  )
)
```


In this case I think it makes more sense to use the second option.
