### ISSUE TITLE
Trouble installing R6

### ISSUE THREAD

**Issue by alexandrosgryparis** [r-lib/R6#182]
Hi, I cannot get R6 installed. Could it be that the reason is that my username on my laptop is in Greek, and it doesn't recognize the fonts? I am getting the following message:

  There is a binary version available but the source version is later:
   binary source needs_compilation
R6  2.3.0  2.4.0             FALSE

installing the source package ‘R6’

trying URL 'https://ftp.cc.uoc.gr/mirrors/CRAN/src/contrib/R6_2.4.0.tar.gz'
Content type 'application/octet-stream' length 31545 bytes (30 KB)
downloaded 30 KB

* installing *source* package 'R6' ...
** package 'R6' successfully unpacked and MD5 sums checked
Error in .read_description(dfile) : 
  file 'C:/Users/ÁëÝîáíäñïò/AppData/Local/Temp/Rtmpmse9yJ/R.INSTALL133033a5e41/R6/DESCRIPTION' does not exist
ERROR: installing package DESCRIPTION failed for package 'R6'
* removing 'C:/R/R-3.5.2/library/R6'
In R CMD INSTALL

The downloaded source packages are in
        ‘C:\Users\ÁëÝîáíäñïò\AppData\Local\Temp\RtmpiMtoWy\downloaded_packages’
Warning message:
In install.packages(NULL, .libPaths()[1L], dependencies = NA, type = type) :
  installation of package ‘R6’ had non-zero exit status

Any ideas on how to work this?

My session info:
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
"LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"

attached base packages:
 ".GlobalEnv"        "package:stats"     "package:graphics"  "package:grDevices" "package:utils"     "package:datasets"  "package:methods"   "Autoloads"         "package:base"  

Thank you

**Comment by gaborcsardi** [comment]
This is a bug in base R. A workaround is to install the older binary package:
```r
install.packages("R6", type = "binary")
```

**Comment by alexandrosgryparis** [comment]
Indeed, it worked. Thanks a lot!
