### ISSUE TITLE
Update a dependent field in R6 object when a parent field is updated

### ISSUE THREAD

**Issue by mcooganj** [r-lib/R6#183]
This isn't really an issue with the package (i don't think) but i am looking for some help and didn't get it when i asked a question on [SO](https://stackoverflow.com/questions/54786182/update-a-dependent-field-in-r6-object-when-a-parent-field-is-updated)

How should I go about updating a field (say area of a quad) when i update one of the inputs (say width)?

**Comment by wch** [comment]
I've answered this over at the SO post.
