### ISSUE TITLE
Factory function that create new class

### ISSUE THREAD

**Issue by jcubic** [r-lib/R6#186]
I was trying multiple things and it don't work. My latest code look like this:
```R
get <- function(x = list()) {
  class <- R6::R6Class(classname = "class")
  for (name in names(x)) {
    class$set("public", name, function() name)
  }
  class
}
x <- get(x = list(a = 10, b = 20))$new()
x$a()
# b
x$b()
# b
```

the first don't work because of closures inside loop but the second don't work because it can't find name in closure

```R
get <- function(x = list()) {
  class <- R6::R6Class(classname = "class")
  lapply(names(x), function(name) {
    print(name)
    class$set("public", name, function() name)
  })
  class
}
x <- get(x = list(a = 10, b = 20))$new()
x$a()
```

So basically what I want to do with this is to have function that create R6Class and where methods take scope from where function is called same as like R6Class (this break referencial transparency because I can't create function that create R6Class and just replace that call to R6Class with that function).

```R
fn <- function() {
    x <- 10
    ## the same code works if I use R6Class function here
    y <- myFunction(public = list(
       foo = function(y) {
          x + y
       }
    })
    z <- y$new()
    z$foo(10)
    ## I want 20 as result
}
```

The reason why I want this so I can remove some boiler plate from my component system written using R6 inside handy function that make code shorter.

I've tried multiple things `eval substitute` changing environment initilizing with NULL and overwriting new function and they all didn't work, is there a way to make function that return R6Class work?

**Comment by jcubic** [comment]
I've found this issue #114 but it didn't help

**Comment by wch** [comment]
Methods in an R6 object have their environment changed when the object is instantiated -- that's how `self` refers to the correct thing.

To do what you want, you'd have to modify the body of the function directly, instead of trying to capture the value in a closure.

You can do this with `eval(substitute())`. For example:

```R
get <- function(x = list()) {
  class <- R6::R6Class(classname = "class")
  lapply(names(x), function(name) {
    fn <- eval(substitute(function() subst_name, list(subst_name = name)))
    class$set("public", name, fn)
  })
  class
}
x <- get(x = list(a = 10, b = 20))$new()
x$a()
```

The rlang package also has powerful and flexible tools for doing this.

**Comment by wch** [comment]
One note about the above code. If you print out `x$a`, R will give this misleading output:

```
> x$a
function() subst_name
<environment: 0x7ff03f977578>
```

This is because it captured the source ref and is printing it out -- roughly speaking, it's not the actual content of the code that gets evaluated, but a text representation of what the code looked like when the function object was created. To avoid confusion, it's best to just get rid of the source ref.


```R
get <- function(x = list()) {
  class <- R6::R6Class(classname = "class")
  lapply(names(x), function(name) {
    fn <- eval(substitute(function() subst_name, list(subst_name = name)))
    attr(fn, "srcref") <- NULL
    class$set("public", name, fn)
  })
  class
}
x <- get(x = list(a = 10, b = 20))$new()
x$a
```

Then it'll print this:


```
> x$a
function () 
"a"
<environment: 0x7ff03ea08530>
```

**Comment by jcubic** [comment]
Thank you very much, I've spend few hours to make it working without success, This is perfect.

**Comment by jcubic** [comment]
Have one more issue, consider this code:

```R
constructor <- function(public = list()) {
  class <- R6::R6Class(classname = "class")
  lapply(names(public), function(name) {
    if (is.function(public[[name]])) {
      fn <- eval(substitute(function(...) fn(...), list(fn = public[[name]])))
      class$set("public", name, fn)
    } else {
      class$set("public", name, public[[name]])
    }
  })
  class
}
set <- function() {
  a <- 10
  x <- constructor(public = list(a = function() { a + self$b }, b = 20))$new()
  x$a()
}

set()
```

this almost work except it can't find `self` name, I think it's because it no longer have encapsulated R6Class environment. Is there a away to also add `private` and `self` to dynamic functions?

**Comment by jcubic** [comment]
For future reference I've found solution:
```R
constructor <- function(public = list(), private = list()) {
  class <- R6::R6Class(classname = "class")
  lapply(names(public), function(name) {
    if (is.function(public[[name]])) {
      env <- environment(public[[name]])
      env$self <- public
      env$private <- private
      fn <- eval(substitute(function(...) fn(...), list(fn = public[[name]], self = public)))
      class$set("public", name, fn)
    } else {
      class$set("public", name, public[[name]])
    }
  })
  class
}
set <- function() {
  a <- 10
  x <- constructor(public = list(a = function() { a + self$b }, b = 20))$new()
  x$a()
}

set()
```

**Comment by pokyah** [comment]
Hi ! 

Thanks for this nice solution that helped me solve a technical problem I encountered. 

The purpose was to automatically append a set of selected functions from [gert](https://docs.ropensci.org/gert/) package as public methods of an object of class Git. An important feature was that the arguments of the methods and their default values where automatically pulled from the gert functions.

Here is how I've achieved this taking inspiration from @jcubic last answer : 

```
gertWrap <- function(public = list(), private = list()) {
  
  body = lapply(public, function(git_fun){
    paste0("{
    call = as.list(match.call())[-1] # first position is the function_name
    custom_args = list(path = setPath(eval(call$path))) # could extend this list for more customization
    overlap_args = names(call) %in% names(custom_args) # handle overlapping args
    if(!any(overlap_args)) call = c(call, custom_args)
    do.call(gert::git_", git_fun, ", call)}")
  })
  
  args = lapply(public, function(fnName){
    purrr::discard(as.list(args(eval(expr = paste0("git_", fnName)))), is.null)
  })
  
  git_funs = purrr::pmap(.l = list(public, args, body), .f = function(methodName, args, body){
    handleArgDefault = function(name, value){
      if(is.character(value)) {value = paste0("'", value, "'")}
      parsed = paste0(name, " = ", value)
      
    }
    args = purrr::map2(names(args),args, handleArgDefault)
    args = paste(args, collapse = ", ")
    eval(parse(text = paste(methodName, '<- function(', args, ') { return(' , body , ')}', sep='')))
  })

  Git <- R6::R6Class(classname = "Git")
  
  lapply(names(git_funs), function(name) {
    if (is.function(git_funs[[name]])) {
      env <- environment(git_funs[[name]])
      env$self <- git_funs
      env$private <- private
      Git$set("public", name, git_funs[[name]])
    } else {
      Git$set("public", name, git_funs[[name]])
    }
  })
  return(Git$new())
}

git_funs = list(
  init = "init",
  status = "status"
)

git = gertWrap(public = git_funs)

git$init()
```

I'm posting it in case it might interest other people who want to build other kinds of wrappers.

Best regards
