### ISSUE TITLE
Is 2.4.1 required for R 4.0?

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/R6#196]
From the NEWS file:

> Cloning active bindings previously relied on buggy behavior in as.list.environment(), which would return the active binding's function definition rather than the value from invoking the function. In R 4.0, the behavior will chang so that it returns the value. R6 now no longer relies on this buggy behavior. (#192)

It sounds like cloning active bindings will very probably break with R 4.0 unless we upgrade  to R6 2.4.1. Is this a fair assessment?

**Comment by wch** [comment]
That's right. The new behavior for R is not currently enabled by default in R-devel, but if you'd like to test it you can turn it on by setting the environment variable `_R_ENV2LIST_BUGFIX_=true` (you'll need to use R-devel for this).
