### ISSUE TITLE
Documentation of methods

### ISSUE THREAD

**Issue by paulstaab** [r-lib/R6#2]
I was wondering if there is a way to to add some documentation/help/instructions to  methods of R6 classes? If not, is something planed in this direction? I guess that integration into `help()` might be difficult, but something like the optional string in the first line of reference class methods that can then printed with $help() would be fantastic.

Great package, thanks!

**Comment by hadley** [comment]
Please see https://roxygen2.r-lib.org/articles/rd.html#r6
