### ISSUE TITLE
Usage of `<<-` vs `<-` in inheritance docs

### ISSUE THREAD

**Issue by ras44** [r-lib/R6#206]
In the [inheritance](https://r6.r-lib.org/articles/Introduction.html#inheritance) section of the docs, private variables are set with `<<-` instead of `<-`.  I'm not sure why that is and I was unable to find explanations for why in the docs.  I reproduced with `<-` and was able to produce the same result, though I'm also unsure if that's more correct.  Would greatly appreciate your insights!

**Comment by wch** [comment]
That's a mistake - thanks for pointing it out.

**Comment by wch** [comment]
Fixed in 949b4fc4.
