### ISSUE TITLE
allow to insulate private environments between inherited classes

### ISSUE THREAD

**Issue by pokyah** [r-lib/R6#235]
Hi,

Here is a short reprex to illustrate my problem:

```
library(R6)

Family <- R6Class(
  "Family",
  private = list(
     shared = {
       env <- new.env()
       env$address <- "1547 Coffman Alley"
       env
     }
   ),
   active = list(
     address = function(value){
       if(missing(value)) return(private$shared$address)
       else private$shared$address <- value
     }
   )
  )

Child <- R6Class(
  "ChildShared", 
   inherit = Family,
  private = list(
    shared = {
      env <- new.env()
      env$school <- "River Bridge School"
      env
    }
  ),
  active = list(
    school = function(value){
      if(missing(value)) return(private$shared$school)
      else private$shared$school <- value
    }
  )
)


mother <- Family$new()
mother$address
child_1 = Child$new()
child_1$address # NULL => why isn't it "1547 Coffman Alley"
child_1$school # ok : "River Bridge School"

```

Why does `child_1$address` is  NULL?

I would expect that my`Child` class would inherits from the `Family` class shared env even if it has is proper shared env. How to allow a child class to have its proper shared env while still inheriting from its parent class shared env? 

Is there a trick or is it a R6 missing feature? 

Thanks for your help.

**Comment by arnaud-feldmann** [comment]
It seems to be some kind of bother, as the field "shared" of the Child class overrides the private field "shared" of the GrandParent class.

In OOP languages like Java or C++ there is no such behaviour, as you can't override a member you're likely to ignore. You can override methods (if they are declared virtual in c++), but then it seems to me that you shouldn't be able to collide with fileds that you could ignore.

I think the correct behaviour would be at least to allow to separate the private environments between the inherited classes. If some people are working to extend a class they take on another package, I think they shouldn't have to care about the private fields. They shouldn't have their work at risk if the maintener of the parent package modifies the private fields of the parent class either.

So an option to have multiple envs for multiple private envs during inheritance would be welcome. Or, simpler, maybe some kind of protected prefix to emulate different namespaces inside the private environments would be fine.

**Comment by pokyah** [comment]
I post the solution to another example provided by @ColinFay in PM.

```
ElectronicsBrand <- R6Class(
  "ElectronicsBrand",
  private = list(
    shared = {
      env <- new.env()
      env$brandName <- "Electronics2000"
      env
    }
  )
)

class_maker <- function(class){
    R6Class(
      class,
      inherit = ElectronicsBrand,
      public = list(
        initialize = function(type) {
          private$shared$type <- type
          invisible(self)
        },
        startupMsg = function() {
          message("Hello ! I'm a ", private$shared$type, " computer made by ", private$shared$brandName)
        }
      ),
      active = list(
        computer_type = function() {
          private$shared$type
        },
        computer_brand = function() {
          private$shared$brandName
        }
      )
    )
}

ComputerFactory <- class_maker("ComputerFactory")

Desktop <- ComputerFactory$new(type = "Desktop")
Desktop$computer_brand 
Desktop$computer_type 
Desktop$startupMsg()
```

Hope it might help other people
