### ISSUE TITLE
remove or modify the outdated Note in 'Introduction' vignette?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/R6#240]
Introduction [vignette](https://r6.r-lib.org/articles/Introduction.html) has the following note, but `{R6}` on [CRAN](https://cran.r-project.org/web/packages/R6/index.html) itself now relies on `R (≥ 3.0)`.

![image](https://user-images.githubusercontent.com/11330453/145011199-2aa7b737-c547-4e2e-ac01-17f0ac7d8070.png)

**Comment by wch** [comment]
No, we should keep this -- the note is about the version of *R6*, not *R*.

**Comment by IndrajeetPatil** [comment]
Oops, my bad!

**Comment by wch** [comment]
This is helpful though -- it reminded me to make a change where R6 prints messages for public finalizers.
