### ISSUE TITLE
bump the package version in the `main` branch?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/R6#241]
- On GitHub:

https://github.com/r-lib/R6/blob/dda25089187f6e15266a964d9119285f98d9ac3d/DESCRIPTION#L3

- On CRAN

![image](https://user-images.githubusercontent.com/11330453/145011642-3cc98d59-b2fb-45f5-93d0-3d7cea2cf833.png)

**Comment by wch** [comment]
Thanks, I've fixed in 94db8c8.
