### ISSUE TITLE
Error building R6 (2.5.1). R version 4.2.2 currently unavailable

### ISSUE THREAD

**Issue by yannsay-impact** [r-lib/R6#271]
Hello,

I was trying the github actions yesterday, in particular [shiny-deploy.yaml](https://github.com/r-lib/actions/blob/v2-branch/examples/shiny-deploy.yaml).

The steps I took were:

- create new shiny app project (from R studio, faithfull geyser), using renv.
- run the app
- deploy the app through the blue button. it deploys correctly. (or using rsconnect::deployApp())
- add the github actions workflow usethis::use_github_action("shiny-deploy.yaml")
- add my secret, token, etc to github repo
- Once pushing, the action stops at the "authorize and deploy" step with that error.

![image](https://user-images.githubusercontent.com/79831444/199667879-57029085-3962-4d79-ad8f-2b83b7ddb252.png)

- I fix it by specifying the r version to be installed in the github actions 4.1 as 4.2. was released yesterday.

The repo can be found [here ](https://github.com/impact-initiatives-research/shiny-cicd-test2/actions).

I am not sure this is the best way to solve my problem. Neither I am sure where to raise this problem as I don't know if the problem comes from the new release of R, or the R6 package or something else.

(I have opened a [discussion](https://community.rstudio.com/t/shiny-deploy-yaml-error-building-r6-2-5-1-r-version-4-2-2-currently-unavailable/151760) on posit community but I did not get an answer) 

Best

**Comment by gaborcsardi** [comment]
Unfortunately I have no clue how `rsconnect::deployApp()` works, my guess would be that R 4.2.2 is not available on shinyapps.io yet.

**Comment by yannsay-impact** [comment]
Another have been opened on [posit.co](https://community.rstudio.com/t/when-is-r-4-2-2-expected-to-be-supported-on-shiny/152052). I will close this issues
