### ISSUE TITLE
Default arguments in R6 class methods are not shown 

### ISSUE THREAD

**Issue by olegshirokikh** [r-lib/R6#79]
Say one has the f-n like this:

```
func <- function(enum = c("b", "d", "c")) {
  arg <- switch(match.arg(enum), a = 1L, b = 2L, c = 3L)
}
```

Then the function signature and default args will pop up suggesting the use of the function:
![image](https://cloud.githubusercontent.com/assets/8054506/11315060/0fad93b0-8fa1-11e5-92ed-742c74facb82.png)

Same thing but in R6 class method:

```
EnumClass <- R6Class("EnumClass",
   portable = FALSE,
   public = list(
     func = function(enum = c("b", "d", "c")) {
       arg <- switch(match.arg(enum), a = 1L, b = 2L, c = 3L)
     }
   ))
```

![image](https://cloud.githubusercontent.com/assets/8054506/11315124/0e6f585c-8fa2-11e5-9e89-c8b57fdc4dca.png)

Is there any way to address this? Thanks

**Comment by wch** [comment]
I think this would require some modifications to the RStudio IDE. cc: @kevinushey

**Comment by hadley** [comment]
This is a bug in RStudio.
